spring:
  application:
    name: lootwise
  datasource:
    url: jdbc:postgresql://localhost:5432/lootwise
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

steam:
  api:
    base-url: https://store.steampowered.com
    reviews-base-url: https://store.steampowered.com
    country-code: KR
    language: koreana
    review-sync-limit: 20
    timeout: 5s
  batch:
    collect-cron: "0 0 */3 * * *"

logging:
  level:
    org.hibernate.SQL: info
